
server:
  port: ${PORT:9000}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param # to get trace use ?trace=true in url
    include-exception: false
spring:
  cloud:
    config:
      enabled: false
  application:
    name: MOCK-EXAMS-SERVICE
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      #create-drop validate create
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/mock-exams
    #url: jdbc:postgresql://localhost:5432/mock-exams
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    #driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      database: mock-exams
      port: 27017
      host: localhost
      authentication-database: admin
      username: rootuser
      password: rootpass
  messages:
    basename: i18n/messages

management:
  endpoints:
    web:
      exposure:
        include:
          - httptrace
          - info
          - env
          - configprops
          - metrics
mock-exams:
  trace: true

